### ISSUE TITLE
No camera image (black screen)

### ISSUE THREAD

**Issue by simontegelid** [googlecreativelab/lines-of-play#1]
When the app is started, after the splash screen has disappeared, just a black background is seen. I expect the camera image to be shown. Camera permissions are granted.

Not sure if it's relevant, but the "View in 3D" AR thing on animals in Chrome works just fine.

Device: Xiaomi Mi 9T Pro
OS: lineage_raphael-userdebug 10 QQ3A.200605.001 eng.abhish.20200615.084122 test-keys 

![Screenshot_20200629-083720_Lines_of_Play](https://user-images.githubusercontent.com/891850/85981161-02dde500-b9e4-11ea-8c8c-f90a07a49361.png)

**Comment by jasmineroberts** [comment]
1. Which version of Unity are you using?
2. Install [Google Play Services for AR](https://play.google.com/store/apps/details?id=com.google.ar.core&hl=en_US) 
3. Do you have "ARCore Supported" checked in the XR Settings?
Go to `File` →` Player Settings ... `→` XRSettings` 
Make sure `ARCore Supported` is checked. 

Refer to the following image:

![image](https://user-images.githubusercontent.com/3989705/86018419-53a90a00-b9f3-11ea-8391-5d163e0c96ee.png)

**Comment by simontegelid** [comment]
I installed it from Google Play, so no Unity version installed. Google Play Services for AR is installed and other AR-apps works (eg. Measure, AR elements). Is something more needed?

**Comment by jasmineroberts** [comment]
Try uninstalling and reinstalling [Google Play Services for AR](https://play.google.com/store/apps/details?id=com.google.ar.core&hl=en_US).

**Comment by simontegelid** [comment]
Still nothing. Cleared cache and storage too.

The version of Lines of play is, according to the Apps menu in android 0.1 and according to the help section of the app 1.2.2 (build 43).

**Comment by kidavid** [comment]
Hi @simontegelid , 

It seems your device may not be compatible with Depth API. There is a subset of ARCore-compatible devices for which Depth API is certified and enabled. Please take a look here: https://developers.google.com/ar/discover/supported-devices

Please look for "Supports Depth API" in the Notes column of each listed device.

David

**Comment by simontegelid** [comment]
Oh, I see. That might explain it. Thanks! Consider adding a note mentioning that in the app to save you from further issue reports 😊

**Comment by jasmineroberts** [comment]
> Oh, I see. That might explain it. Thanks! Consider adding a note mentioning that in the app to save you from further issue reports 😊

In the README,  there is mention and a link to the device compatibility page. 
We can try to link that page on the Play Store listing though. Great idea!
